### sub
GET http://localhost:8765/kkmq/sub?t=a&cid=kk

### send
POST http://localhost:8765/kkmq/send?t=a&cid=kk
Content-Type: application/json

{
  "body" : "{\"id\":5,\"item\":\"item3\",\"price\":3.0}"
}

### recv
GET http://localhost:8765/kkmq/recv?t=a&cid=kk

### ack
GET http://localhost:8765/kkmq/ack?t=a&cid=kk&offset=3